version: '3.6'
services:
  postgres-test:
    image: postgres:11.9
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DBNAME}
    ports:
      - '5433:5432'

volumes:
  postgres_data:
